/**
 * VideoBackground — Cinematic AI-generated video background for Remotion scenes
 *
 * Renders an AI-generated clip (from fal.ai / LongCat) as a full-bleed background.
 * If the clip is not yet generated, renders null so the existing CSS animation shows.
 *
 * Clip files are generated by: node generate-clips.js
 * They land in /public/clips/<clipId>.mp4
 */

import React from 'react';
import { Video, staticFile, useCurrentFrame, useVideoConfig, interpolate } from 'remotion';

interface VideoBackgroundProps {
  /** Clip ID matching the id field in generate-clips.js CLIPS array */
  clipId: string;
  /** Overall opacity of the video layer (0–1). Default: 0.35 for atmospheric background */
  opacity?: number;
  /** Additional blend overlay: 'multiply' | 'screen' | 'overlay' | 'none' */
  blendMode?: React.CSSProperties['mixBlendMode'];
  /** Zoom scale for cinematic feel — e.g. 1.05 for slow push-in */
  scale?: number;
  /** Playback speed multiplier. Default: 1 */
  playbackRate?: number;
  /** Fade in over this many frames. Default: 20 */
  fadeInFrames?: number;
}

// Clips that have been successfully generated (add clip IDs here after running generate-clips.js)
// The component reads this list to decide whether to render <Video> or null
const AVAILABLE_CLIPS = new Set<string>(
  // After running `node generate-clips.js`, paste generated clip IDs here, e.g.:
  // ['intro_bg', 'cloud_bg', 'ai_bg']
  (process.env.REMOTION_AVAILABLE_CLIPS || '').split(',').filter(Boolean)
);

export const VideoBackground: React.FC<VideoBackgroundProps> = ({
  clipId,
  opacity = 0.35,
  blendMode = 'normal',
  scale = 1.04,
  playbackRate = 1,
  fadeInFrames = 20,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // If clip not yet generated, render nothing — CSS animation shows through
  if (!AVAILABLE_CLIPS.has(clipId)) {
    return null;
  }

  const fadeOpacity = interpolate(frame, [0, fadeInFrames], [0, opacity], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        overflow: 'hidden',
        zIndex: 0,
      }}
    >
      <Video
        src={staticFile(`clips/${clipId}.mp4`)}
        style={{
          width: '100%',
          height: '100%',
          objectFit: 'cover',
          opacity: fadeOpacity,
          mixBlendMode: blendMode,
          transform: `scale(${scale})`,
          transformOrigin: 'center center',
        }}
        playbackRate={playbackRate}
        muted
      />
      {/* Dark gradient overlay for text readability */}
      <div
        style={{
          position: 'absolute',
          inset: 0,
          background:
            'linear-gradient(180deg, rgba(3,7,18,0.5) 0%, rgba(3,7,18,0.2) 50%, rgba(3,7,18,0.6) 100%)',
        }}
      />
    </div>
  );
};
